const express =require('express')
const app =express()
const cors=require('cors')
const router=require('./Routers/router')
const router1=require('./Routers/router1')
app.use(cors())
app.use('/insert',router)
app.use('/getdata',router1)
app.listen(3336,()=>{console.log('chalo bhai')})